### ISSUE TITLE
Can't run after fresh install on Ubuntu 22.04

### ISSUE THREAD

**Issue by info-git** [BlueHatbRit/mdpdf#144]
Installed with npm install mdpdf -g
```
$ mdpdf

/usr/local/lib/node_modules/mdpdf/src/index.js:174
      await page.goto('file:' + tempHtmlPath, { waitUntil: options.waitUntil ?? 'networkidle0' });
                                                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/mdpdf/bin/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by BlueHatbRit** [comment]
Hi there, what version of nodejs and npm are you running? This looks to me like your version of node might be old.

**Comment by info-git** [comment]
Hello
Yeah that might be it
```bash
$ npm --version
8.5.1
```
```bash
$ nodejs --version
v12.22.9
```
I'm gonna try and see if there's upgrade instructions I can use

**Comment by info-git** [comment]
OK. Got it working by following the instructions for the NVM method @ https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-22-04
Working version of `node` is `v16.14.0`
