### ISSUE TITLE
Phantom.js missing

### ISSUE THREAD

**Issue by banditopazzo** [BlueHatbRit/mdpdf#47]
Hi,

I had to install the phantomjs-prebuilt package manually. Probably i'ts missing in the dependencies.

Bye

**Comment by BlueHatbRit** [comment]
This isn't a problem I've had in the past at all, could you elaborate a bit more and possibly provide the error messages you got while performing the npm install? I've not seen this reported by anyone in the past either. It could be a broken dependency further up the tree due an unfixed version or something.

**Comment by banditopazzo** [comment]
Hi, there is not a problem with the installer, the installer works fine ( globally installed ). But then if I execute `mdpdf filename.md` there is an error about phantom.js because it's not found. I solved going into the directory of the package ( /usr/lib/node_modules/mdpdf/ ) and doing npm install phantomjs-prebuild. After that, no errors, and the markdown file is converted to a pdf.

**Comment by BlueHatbRit** [comment]
@banditopazzo I can't seem to recreate the issue. I've just tried a fresh global install from the npm registry and immediately run `mdpdf` on a markdown file and had no issues at all.

Could you give me the full error you were getting before you did the fix you mentioned?

**Comment by banditopazzo** [comment]
Hi, I uninstalled and reinstalled with:
`npm install mdpdf -g`

The installer outputs this:
```
/usr/bin/mdpdf -> /usr/lib/node_modules/mdpdf/bin/index.js

> phantomjs-prebuilt@2.1.16 install /usr/lib/node_modules/mdpdf/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /usr/lib/node_modules/mdpdf/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1535362712155/phantomjs-2.1.1-linux-x86_64 -> /usr/lib/node_modules/mdpdf/node_modules/phantomjs-prebuilt/lib/phantom
chmod failed: phantomjs was not successfully copied to /usr/lib/node_modules/mdpdf/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 (node_modules/mdpdf/node_modules/phantomjs-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ mdpdf@1.7.0
added 158 packages from 114 contributors in 14.761s
```

If I run `mdpdf` on a markdown file, it gives me this error:
```
html-pdf: Failed to load PhantomJS module. { Error: Cannot find module 'phantomjs-prebuilt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/mdpdf/node_modules/html-pdf/lib/pdf.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/mdpdf/node_modules/html-pdf/lib/index.js:1:73)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32) code: 'MODULE_NOT_FOUND' }
{ AssertionError [ERR_ASSERTION]: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'
    at new PDF (/usr/lib/node_modules/mdpdf/node_modules/html-pdf/lib/pdf.js:38:3)
    at Object.createPdf [as create] (/usr/lib/node_modules/mdpdf/node_modules/html-pdf/lib/index.js:10:14)
    at Promise (/usr/lib/node_modules/mdpdf/index.js:177:7)
    at Promise._execute (/usr/lib/node_modules/mdpdf/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/mdpdf/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/lib/node_modules/mdpdf/node_modules/bluebird/js/release/promise.js:79:10)
    at createPdf (/usr/lib/node_modules/mdpdf/index.js:176:9)
    at readFile.then.then.then.then.md (/usr/lib/node_modules/mdpdf/index.js:169:10)
    at tryCatcher (/usr/lib/node_modules/mdpdf/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/mdpdf/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/mdpdf/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/mdpdf/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/mdpdf/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/mdpdf/node_modules/bluebird/js/release/promise.js:638:18)
    at /usr/lib/node_modules/mdpdf/node_modules/bluebird/js/release/nodeback.js:42:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '==' }
```

To fix I have to go to `/usr/lib/node_modules/mdpdf` and type in the terminal:
`npm install phantomjs-prebuilt`
and outputs this:
```
> phantomjs-prebuilt@2.1.16 install /usr/lib/node_modules/mdpdf/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /usr/lib/node_modules/mdpdf/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1535363234926/phantomjs-2.1.1-linux-x86_64 -> /usr/lib/node_modules/mdpdf/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/lib/node_modules/mdpdf/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm notice created a lockfile as package-lock.json. You should commit this file.
+ phantomjs-prebuilt@2.1.16
added 66 packages from 72 contributors and audited 418 packages in 5.316s
found 0 vulnerabilities
```

I don't understand what is the problem but this solution works for me. I hope it helps

**Comment by banditopazzo** [comment]
My specs:
node v10.9.0
npm 6.4.0

**Comment by BlueHatbRit** [comment]
It seems during the Phantom installation you had the error:

```
chmod failed: phantomjs was not successfully copied to /usr/lib/node_modules/mdpdf/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
```

Googling around, it seems this is some sort of permission error that is prevalent on linux when installing phantom dependant projects. I don't have a linux machine handy, only macOS or Windows so I can't test this myself but it might be worth trying the installation with `sudo` to see what happens.

I'll spin up a vm when I get a chance, but I'm currently on vacation so away from my usual machine.

**Comment by BlueHatbRit** [comment]
@banditopazzo I've given this a go using a docker container as suggested by @enric1994 in the above comment. The issue is definitely due to file permissions. You need to set the correct file permissions on the `/usr/lib/node_modules` directory (and sub directories). Alternative, if you're feeling brave you can use `sudo npm install mdpdf -g`. This should let you install it just fine, but be aware that there are risks by giving sudo privileges to an npm install.

**Comment by BlueHatbRit** [comment]
I'm going to close this for now as resolved, if this doesn't fix your issue let me know and I'll re-open the issue and continue debugging it with you.

**Comment by banditopazzo** [comment]
Sorry for the long delay. I have used `sudo npm install mdpdf -g`, and however phantomjs was not installed. For me there is no working solution right now apart the workaround above. I don't know where the issue come from, maybe you can add a temporary "Known Issues" section on the Readme. Probably I will test it again in the future, now I resolved with the workaround

**Comment by BlueHatbRit** [comment]
@banditopazzo what OS are you using? It would be ideal if I could reproduce this so it can get fixed rather than adding a workaround onto the readme but if we can't resolve it then I'll consider an FAQ section on there with a link to this issue.

**Comment by BlueHatbRit** [comment]
This will be fixed in the v2.x released over the last few days. I've replaced Phantom with Puppeteer so you definetely won't get this issue anymore 🎉 sorry it's taken so long, I just do this in my spare time when I get some.

**Comment by BlueHatbRit** [comment]
Just edited my above comment as I realised it was ambigious, the release went out over the last few days so it _is_ fixed not _will be_ fixed 😄
