### ISSUE TITLE
Error creating PDF's on Windows

### ISSUE THREAD

**Issue by BlueHatbRit** [BlueHatbRit/mdpdf#6]
## Issue
When creating a PDF on windows, we get the following error:

```
Error: html-pdf: Evaluation - ReferenceError: Can't find variable: hljs
Stack:
  at undefined

    at ChildProcess.<anonymous> (E:\code\mdpdf\node_modules\html-pdf\lib\pdf.js:121:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

## Hypothesis
This seems to be due to the code on lines 8 and 9 in [layout.hbs](./https://github.com/BlueHatbRit/mdpdf/blob/1.2.2/layout.hbs). According to the PhantomJS docs, `evaluate()` runs in a Sandbox which means it runs the main highlightJs script on line 8, and then for line 9 it has no reference to the variable `hljs`. This means we can't get syntax highlighting in our PDFs on Windows.

I've tried moving this snippet of code into the main highlightJs file and it seems fine on the HTML output but the PhantomJS isn't rendering any colouring. I'm not really sure what's going on here but it seems to be to do with PhantomJS so I'm going to begin narrowing it down and trying to remove mdpdf and html-pdf from the equation to see if the issue persists. If it is in PhantomJS then it would be good to try and patch it for them, we should at least submit a bug report.

**The odd thing is this only happens on Windows, on OSX it seems fine. I don't have access to Linux to test it right now but I'll try it on a VM as soon as I can get to my laptop.**

## Next steps
A proper test to see if it's PhantomJS would be to create a small file HTML file with two script tags, the second one should make use of a declared variable from the first. This should then be pushed into PhantomJS and saved out as a PDF to see if it errors out on us.

**Comment by BlueHatbRit** [comment]
It seems that this could actually be to do with html-pdf's default PhantomJS script "pdf_a4_portrait.js" which seems to orchestrate the page loading and rendering.

However this doesn't really line up if the issue is only on Windows as there are no platform specific clauses in the code. Digging into this script further to fully understand how it evaluates content.

**Comment by BlueHatbRit** [comment]
Moving the hljs script line `hljs.initHighlightingOnLoad();` inside the main highlight.pack.js seems to remove the errors and the highlighting is working in the debug HTML output but not the final PDF.

I'll test this on OSX and Ubuntu later and see if it's working correctly there. If that is confirmed then I will add that as a temporary fix meaning highlighting will not work on Windows but the conversion will succeed.

**Comment by BlueHatbRit** [comment]
I've tried pulling in highlight.pack.js using a file read and injecting it with handlebars but this seems to yield syntax errors in the HTML for some reason.
